### ISSUE TITLE
Fail on multiples webresource's

### ISSUE THREAD

**Issue by i0n-** [chrisprice/phonegap-build#24]
When I use this configuration on my pom.xml

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.5</version>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exploded</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <webResources>
                        <resource>
                            <directory>src/main/template</directory>
                        </resource>
                        <resource>
                            <directory>src/main/template-develop</directory>
                        </resource>
                    </webResources>
                </configuration>
            </plugin> 

throw this exception:

    Failed to execute goal com.github.chrisprice:phonegap-build-maven-plugin:0.0.9:build (default) on project frontend: Execution default of goal com.github.chrisprice:phonegap-build-maven-plugin:0.0.9:build failed: Build error : Unable to add 'assets/plugins/tables_datatables/extras/ColVis/media/js/ColVis.min.js.gz': file already in archive -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.chrisprice:phonegap-build-maven-plugin:0.0.9:build (default) on project frontend: Execution default of goal com.github.chrisprice:phonegap-build-maven-plugin:0.0.9:build failed: Build error : Unable to add 'assets/plugins/tables_datatables/extras/ColVis/media/js/ColVis.min.js.gz': file already in archive
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
            at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
            at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
            at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
            at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
            at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
            at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
            at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
            at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
            at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:606)
            at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
            at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
            at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
            at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.chrisprice:phonegap-build-maven-plugin:0.0.9:build failed: Build error : Unable to add 'assets/plugins/tables_datatables/extras/ColVis/media/js/ColVis.min.js.gz': file already in archive
            at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
            ... 19 more
    Caused by: com.github.chrisprice.phonegapbuild.api.ApiException: Build error : Unable to add 'assets/plugins/tables_datatables/extras/ColVis/media/js/ColVis.min.js.gz': file already in archive
            at com.github.chrisprice.phonegapbuild.api.managers.AppsManagerImpl.downloadApp(AppsManagerImpl.java:119)
            at com.github.chrisprice.phonegapbuild.plugin.utils.AppDownloaderImpl.downloadArtifacts(AppDownloaderImpl.java:33)
            at com.github.chrisprice.phonegapbuild.plugin.BuildMojo.execute(BuildMojo.java:321)
            at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
            ... 20 more

Because I intentionally overwrite files, so please allow it.

Thanks.

**Comment by chrisprice** [comment]
@i0n-, the error you're seeing is coming from the PhoneGap Build API i.e. it is a restriction of the service rather than something wrong with the plugin itself. You can see this for yourself in the code relating to the stack trace -

https://github.com/chrisprice/phonegap-build/blob/phonegap-build-0.0.9/api/src/main/java/com/github/chrisprice/phonegapbuild/api/managers/AppsManagerImpl.java#L119

Unfortunately I don't use the service anymore so I'm not sure what's likely to be going wrong in your config... :/
