### ISSUE TITLE
NPE on configuration mismatch

### ISSUE THREAD

**Issue by fiveop** [chrisprice/phonegap-build#25]
If my config.xml contains entries for just one platform (in my case android) and the plugin configuration in my pom.xml mentions two platforms (in my case android and windows phone), I get the following exception:

    Caused by: java.lang.NullPointerException
            at com.github.chrisprice.phonegapbuild.api.managers.AppsManagerImpl.downloadApp(AppsManagerImpl.java:107)
            at com.github.chrisprice.phonegapbuild.plugin.utils.AppDownloaderImpl.downloadArtifacts(AppDownloaderImpl.java:33)
            at com.github.chrisprice.phonegapbuild.plugin.BuildMojo.execute(BuildMojo.java:342)
            at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

(Just in case it matters: I had windows phone in the config.xml previously for a few weeks and then commented it out)

**Comment by chrisprice** [comment]
Thanks for the report @fiveop. As I'm not using the plugin myself anymore and you've found a workaround I won't be fixing it. However, I'll leave the issue open in case it helps anyone else or someone feels inspired to fix it.
